### ISSUE TITLE
Meta objects to be optional in requests

### ISSUE THREAD

**Issue by JBRedcrewAdmin** [ConsumerDataStandardsAustralia/standards-staging#152] opened 2022-03-24 04:52 UTC
**Description**
Meta objects to be optional in requests (specifically for energy)

**Comment by JamesMBligh** [comment] 2023-03-14 02:56
Duplicate of issue #245

**Comment by JamesMBligh** [comment] 2023-03-20 02:28
Fixed in v1.22.1

**Closed** 2023-03-20 02:32 UTC
Labels: bug, in progress
